### ISSUE TITLE
Kubernetes support for core_instance

### ISSUE THREAD

**Issue by niedbalski** [calyptia/cli#108]
# Bug Report

## Describe the bug

Based on #60 

- [X] cli: Implement create core_instance for k8s
- [X] cli: Implement delete core_instance for k8s
- [X] cli: Implement update core_instance for k8s
- [X] cli: Implement get core_instances for k8s
- [X] cloud-docs: Document create core_instance for k8s 
- [x] cloud-docs: Document update core_instance for k8s
- [x] cloud-docs: Document delete core_instance for k8s
- [X] cloud-e2e: Implement tests for create core_instance for k8s
- [X] cloud-e2e: Implement tests for delete core_instance for k8s
- [X] cloud-e2e: Implement tests for update core_instance for k8s
- [X] cloud-e2e: Implement tests for get core_instances for k8s

**Comment by niedbalski** [comment]
@gabrielbussolo there are a couple of items on this list that needs finish before marking this as done. Assigning it to you.

**Comment by gabrielbussolo** [comment]
Docs:
Updating the instance: https://docs.calyptia.com/docs/using-calyptia-cli
Deleting the instance: https://docs.calyptia.com/docs/using-calyptia-cli-1

**Comment by niedbalski** [comment]
@gabrielbussolo @niedbalski @nicolasparada great work on this item folks. Marking it as closed as is fully documented, tested and implemented.
