### ISSUE TITLE
detect current core instance on machine and use that as default

### ISSUE THREAD

**Issue by nicolasparada** [calyptia/cli#118]
Add a way to detect the current core instance on the machine and use that as default value for the `--aggregator` flag in some of the commands. For example:
```bash
calyptia create pipeline
```
Could not need to specify `--aggregator` if we detect that we are running in a VM with a core instance already setup.

**Comment by niedbalski** [comment]
What would be the use case for this?

**Comment by nicolasparada** [comment]
See the discussion here https://calyptia.slack.com/archives/C02SML63BQA/p1660316343394499

**Comment by niedbalski** [comment]
@patrick-stephens @nicolasparada 🤔  the CLI running on the same VM as core, if that's the case, the environment should have CALYPTIA_CLOUD_AGGREGATOR_NAME set, why not using that? --aggregator ${CALYPTIA_CLOUD_AGGREGATOR_NAME}

**Comment by patrick-stephens** [comment]
You have to source it certainly from the file, I've not made it available to everyone. I could do this as well, this was prior to persisting it.

**Comment by niedbalski** [comment]
@patrick-stephens lets do it that way for now.
