### ISSUE TITLE
macOS: Install Wizard

### ISSUE THREAD

**Issue by edsiper** [calyptia/cli#137]
# New feature request

## Describe the proposal

Calyptia CLI for macOS should have a proper installer/wizard.

**Comment by cosmo0920** [comment]
We already have auto generated homebrew formula:
https://github.com/calyptia/cli/blob/main/.goreleaser.yml#L21-L28

We can publish this generated formula as:
https://github.com/calyptia/homebrew-cli

Then, we can tag as:

```console
$ brew tap calyptia/cli
```

But now, we're still unsuccessful to install calyptia CLI via homebrew:

```console
$ brew tap calyptia/cli
==> Tapping calyptia/cli
Cloning into '/opt/homebrew/Library/Taps/calyptia/homebrew-cli'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failure while executing; `git clone https://github.com/calyptia/homebrew-cli /opt/homebrew/Library/Taps/calyptia/homebrew-cli --origin=origin --template=` exited with 128.
```

So, we should only publish automatically generated homebrew formula (dist/calyptia.rb) in https://github.com/calyptia/homebrew-cli repo.

Note that GoReleaser does not support macOS's installer mechanism:
https://github.com/goreleaser/goreleaser/issues/744

Thus, supporting to install via homebrew seems to be enough for macOS installation.

**Comment by cosmo0920** [comment]
With further investigation, we can add post hooks script for creating macOS pkg installers:
https://github.com/calyptia/cli/commit/a6b66d22f8194c9b41365e31b1b0f00fd6fe9476

But I'm not sure how to handle these generated installers via GoReleaser....
