### ISSUE TITLE
Homebrew CLI for Calyptia

### ISSUE THREAD

**Issue by edsiper** [calyptia/cli#138]
# New feature request

## Describe the proposal

Calyptia CLI should be east to get and install. Most macOS users have Homebrew. Azure CLI can be installed with `brew`. We should have our formula there available too: `brew install calyptia-cli`

**Comment by nicolasparada** [comment]
This can be easily added throught goreleaser :)
On nice side-effect of doing it through a package manager like brew is that we can automatically install the autocompletions :D

**Comment by edsiper** [comment]
can be done today ?

**Comment by nicolasparada** [comment]
I'm focusing on pipelines fluent-bit config validation today
