### ISSUE TITLE
Code signing

### ISSUE THREAD

**Issue by nicolasparada** [calyptia/cli#16]
Add code signing to releases to avoid permissions or antivirus issues on OS.

## MAC OS

- https://www.kencochrane.com/2020/08/01/build-and-sign-golang-binaries-for-macos-with-github-actions/
- https://github.com/mitchellh/gon#usage-with-goreleaser

**Comment by niedbalski** [comment]
Not prioritising this work for the time being.  Re-open if requested by product/customer.
