### ISSUE TITLE
Remove version number from binary tarball name in release

### ISSUE THREAD

**Issue by patrick-stephens** [calyptia/cli#191]
# New feature request

## Describe the proposal

To simplify documentation links we can provide direct downloads of latest releases from <https://github.com/calyptia/cli/releases/latest>.
Unfortunately the binaries themselves include the specific version number in the tarball so we cannot link directly to a "latest" tarball.
If we stripped the version number we could or if we added a release link to the tarball generically that would also work - similar to the source link.

### Checklist for proposal reviewer

- [ ] The proposal is clear on what changes need to be made in the code base.

- [ ] The proposal is clear on the architectural changes that will be affected.

- [ ] The proposal is clear on the breaking changes and how to mitigate them.

- [ ] The proposal is clear on what the deployment/configuration strategy is.

- [ ] The proposal is clean on how testing will validate the feature implementation.

### Reviewers

- [ ] Reviewed by a team member of the @calyptia/backend team
- [ ] Reviewed by a product owner.

### Disclaimers

- If there are multiple solutions, please present each one separately.
- Save comparisons for the very end.
- Please do not create a Pull Request without creating an issue first.
- Any change needs to be discussed before proceeding.
- Failure to do so may result in the rejection of the pull request.

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed.
