### ISSUE TITLE
calyptia top failures with missing information

### ISSUE THREAD

**Issue by patrick-stephens** [calyptia/cli#198]
# New feature request

## Describe the proposal

The error flows for `calyptia top` could be improved.

`calyptia top project` : if not project token is provided then this brings up a blank `top`-style view but with the error message about an invalid id. It would be better to fail earlier without switching to `top` mode.

The other two options also do not give help for missing arguments:

```
$ calyptia top agent
Error: accepts 1 arg(s), received 0
$ calyptia top pipeline
Error: accepts 1 arg(s), received 0
```

This is for version 0.40.0.

### Checklist for proposal reviewer

- [ ] The proposal is clear on what changes need to be made in the code base.

- [ ] The proposal is clear on the architectural changes that will be affected.

- [ ] The proposal is clear on the breaking changes and how to mitigate them.

- [ ] The proposal is clear on what the deployment/configuration strategy is.

- [ ] The proposal is clean on how testing will validate the feature implementation.

### Reviewers

- [ ] Reviewed by a team member of the @calyptia/backend team
- [ ] Reviewed by a product owner.

### Disclaimers

- If there are multiple solutions, please present each one separately.
- Save comparisons for the very end.
- Please do not create a Pull Request without creating an issue first.
- Any change needs to be discussed before proceeding.
- Failure to do so may result in the rejection of the pull request.

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed.
