### ISSUE TITLE
Add support for ingest-checks (CLI side) 

### ISSUE THREAD

**Issue by niedbalski** [calyptia/cli#217]
# Bug Report

## Describe the bug

After landing https://github.com/calyptia/core/pull/252 , we should add support in the CLI
to allow full cloud-e2e testing of this feature.

## Description of the implementation.

- calyptia create ingest-check  [--retries --config-section-id]
- calyptia delete ingest-check id (only removes it from the API).
// Probably in a posterior version - calyptia update ingest-check [--retries --config-section-id] --status ()
- calyptia get ingest-check id
- calyptia get ingest-checks

## Which versions are affected

Latest.

**Comment by agup006** [comment]
Is there any documentation on how this works?

**Comment by niedbalski** [comment]
@agup006 I just submitted a doc PR for this https://app.gitbook.com/o/-MUQ1eTVMK9HnM2ck877/s/6SsQES6Kb0NiJMmAuVDw/~/changes/W0F37kAQJ5yZ5DHqpZdJ/pipelines/ingest-checks
