### ISSUE TITLE
CLI: Installation check report.

### ISSUE THREAD

**Issue by niedbalski** [calyptia/cli#229]
# Bug Report

## Describe the bug

After brew install or installing the binary directly, a quick set of checks has to be performed
in the local machine to ensure further operations will work:

1. Ensure the token is set.
2. Ensure the cloud API endpoint is reachable with the given token (this can be performed with any simple get/listing operation).
3. Ensure SSL verification passes (trying to connect to https://cloud-api.calyptia.com/) 
4. Ensure the kubernetes cluster credentials are available. 
5. Ensure the kubernetes cluster is reachable (this can be used the healthcheck endpoint).

This can be implemented all client side, with a few observations:

1. Each step has to be run sequentially (with a :waiting: icon) + a ✅  when ready or a ❌  when failed and explain why.
2. This has to be implemented as an independent command (calyptia check-install) 

Also documented in docs.calyptia.com 

- [ ] Implement checks
- [ ] Write docs for calyptia

**Comment by niedbalski** [comment]
What is the progress on this @gabrielbussolo ?

**Comment by gabrielbussolo** [comment]
I was doing the check each time before a command, i think we can take advantage of the `calyptia config` alias and add a `check`

**Comment by niedbalski** [comment]
@agup006 @patrick-stephens would be good to get your input here.

**Comment by patrick-stephens** [comment]
+1, I'd really start with a `support` top-level command we can expand. Having the user know they can use the CLI for everything will be great - we can expand it to collect this into a tarball and auto-create support requests, etc. in the future.

**Comment by jasmingacic** [comment]
If I'm not mistaken this has already been done in https://github.com/calyptia/cli/pull/256
Should we move this into "In Review"?

**Comment by patrick-stephens** [comment]
yeah this is the issue not the PR

**Comment by gabrielbussolo** [comment]
we already opened and closed this issue a few times, last time we said that a script would do it, is this still relevant for cli @niedbalski @patrick-stephens @jasmingacic

**Comment by patrick-stephens** [comment]
We added some pre and post-install checks to the install script: e.g. https://github.com/calyptia/core-images/blob/4b87eb2ff2593fb124511600944de06f35c7e8ed/vm/install-core.sh#L302-L347

However I would like to have these in the CLI as a simple to invoke command, similar to the feature request for a command to create a support request that captures everything required easily.

The install script can then just invoke the CLI option once it is present.

**Comment by niedbalski** [comment]
Might be a good idea, certainly not prioritising now @gabrielbussolo, please feel free to add this as an item to the https://app.asana.com/0/1205042382663691/1205042407034748, I am closing this issue in favour of that.

**Comment by niedbalski** [comment]
Re-opening to test asana workflow

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed. Please re-open in asana if this surfaces as a priority.
