### ISSUE TITLE
Add preflight check to validate quotas not exceeded

### ISSUE THREAD

**Issue by patrick-stephens** [calyptia/cli#251]
# New feature request

## Describe the proposal

When creating new instances, if we have exceeded our quota limits then the deployment ends up in a crash-loop and you have to inspect the logs of the pods to see why.

It would be better to do a quick check that we have a new instance available before we try to deploy it and then report a more meaningful error directly to the user.

A dev/hidden flag to ignore quotas for POCs, etc. would be useful too.

### Checklist for proposal reviewer

- [ ] The proposal is clear on what changes need to be made in the code base.

- [ ] The proposal is clear on the architectural changes that will be affected.

- [ ] The proposal is clear on the breaking changes and how to mitigate them.

- [ ] The proposal is clear on what the deployment/configuration strategy is.

- [ ] The proposal is clean on how testing will validate the feature implementation.

### Reviewers

- [ ] Reviewed by a team member of the @calyptia/backend team
- [ ] Reviewed by a product owner.

### Disclaimers

- If there are multiple solutions, please present each one separately.
- Save comparisons for the very end.
- Please do not create a Pull Request without creating an issue first.
- Any change needs to be discussed before proceeding.
- Failure to do so may result in the rejection of the pull request.

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed. Please re-open in asana if this surfaces as a priority.
