### ISSUE TITLE
Provide example config generation

### ISSUE THREAD

**Issue by patrick-stephens** [calyptia/cli#253]
# New feature request

## Describe the proposal

Provide a command to auto-generate a valid `fluent-bit.conf` we can use for creating a pipeline - this could be a flag on the `calyptia create pipeline` command.
This will be useful for auto-testing and for customer demos to simplify things.

The default configuration could be extended as we iterate to provide Vivo output, etc. 
If we had a dedicated `calyptia generate config` subcommand then we can use this to allow a user to create config programmatically as they require and we ensure it is valid.

### Checklist for proposal reviewer

- [ ] The proposal is clear on what changes need to be made in the code base.

- [ ] The proposal is clear on the architectural changes that will be affected.

- [ ] The proposal is clear on the breaking changes and how to mitigate them.

- [ ] The proposal is clear on what the deployment/configuration strategy is.

- [ ] The proposal is clean on how testing will validate the feature implementation.

### Reviewers

- [ ] Reviewed by a team member of the @calyptia/backend team
- [ ] Reviewed by a product owner.

### Disclaimers

- If there are multiple solutions, please present each one separately.
- Save comparisons for the very end.
- Please do not create a Pull Request without creating an issue first.
- Any change needs to be discussed before proceeding.
- Failure to do so may result in the rejection of the pull request.

**Comment by patrick-stephens** [comment]
@agup006 / @niedbalski I think this is what Walmart are after as well: https://fluent-all.slack.com/archives/C04F4HARPGE/p1671543548602209
```
Can anyone give me a definition file for service pipeline?
```

**Comment by jasmingacic** [comment]
```bash
# calyptia create pipeline --core-instance useful-rainmaker-1f67
Error: could not read config file: could not open file: open fluent-bit.conf: no such file or directory
exit status 1
```
Create pipeline command expects `--config-file` parameter to be provided. So I'm not sure what we can generate out of this command.
One option would be to add a "wizard" that would prompt the user to provide config values interactively something similar to 
```bash
# calyptia create pipeline --core-instance useful-rainmaker-1f67
Please provide [SERVICE] parameters:
HTTP_Server (Default On): 
HTTP_Listen  (Default 0.0.0.0):
HTTP_PORT (Default 2020):
Log_Level (Default debug):
```

What do you think @patrick-stephens?

**Comment by agup006** [comment]
I would not opt for this interactive session, perhaps print a message to go to the UI console

**Comment by nicolasparada** [comment]
Maybe we can have a `calyptia demo` that setups a core instance, and a couple of pipelines with some common, generic configs for demo purposes.

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed.
