### ISSUE TITLE
Easy access to local core_instance

### ISSUE THREAD

**Issue by patrick-stephens** [calyptia/cli#254]
# New feature request

## Describe the proposal

When creating a new core_instance it would be useful to have the following:
1. Detain a `last_created_instance` name/id setting we can then use if not defined when creating pipelines.
2. Provide a means to get local `core_instance` names/ids deployed to `kubernetes`.

This will simplify automation and testing use cases where we create the core instance then have to parse the response or look at the deployments created - and then rely on assumptions about what the CLI does which may change between versions.

A simple workflow is then reduced further to:

```shell
$ calyptia create core_instance kubernetes --token XXX
$ calyptia create pipeline [--config_file ...]
```

Ideally combine with #253 to mean we can have a fully working config with minimal effort.

### Checklist for proposal reviewer

- [ ] The proposal is clear on what changes need to be made in the code base.

- [ ] The proposal is clear on the architectural changes that will be affected.

- [ ] The proposal is clear on the breaking changes and how to mitigate them.

- [ ] The proposal is clear on what the deployment/configuration strategy is.

- [ ] The proposal is clean on how testing will validate the feature implementation.

### Reviewers

- [ ] Reviewed by a team member of the @calyptia/backend team
- [ ] Reviewed by a product owner.

### Disclaimers

- If there are multiple solutions, please present each one separately.
- Save comparisons for the very end.
- Please do not create a Pull Request without creating an issue first.
- Any change needs to be discussed before proceeding.
- Failure to do so may result in the rejection of the pull request.

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed.
