### ISSUE TITLE
Ensure we set up default permissions and security context

### ISSUE THREAD

**Issue by patrick-stephens** [calyptia/cli#272]
# Bug Report

## Describe the bug

Related to https://github.com/calyptia/core-docker-desktop-extension/issues/75#issuecomment-1342938259
We should follow the approach of the OSS helm chart I think to ensure we have relevant permissions for cluster logging - and also fr filesystem permissions in Openshift.

https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/templates/clusterrole.yaml

## Which versions are affected

Please include component versions and any versioning information that is relevant
to reproduce.

## Reproducer steps

Logical enumerated sequence on how to reproduce the issue.

## Example code or configuration

```
Configuration or code that reproduces the issue
```

## Expected behavior

Please explain what should happen

## Current behavior

Please explain the current behavior

*Disclaimer: Please do not create a Pull Request without creating an issue first.*
Any change needs to be discussed before proceeding.
Failure to do so may result in the rejection of the pull request.

**Comment by patrick-stephens** [comment]
This impacts Openshift as well.

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed. Please re-open in asana if this surfaces as a priority.
