### ISSUE TITLE
[FEATURE] Implement fleet management (CLI side).

### ISSUE THREAD

**Issue by niedbalski** [calyptia/cli#287]
# New feature request

## Describe the proposal

Based on the discussion RFC[0], a new project level object named fleet has to be created.

A set of sub-commands needs to be implemented:
```
calyptia get fleet  
calyptia delete fleet  [--tags]
calyptia update fleet [--config-file] [--tags]
calyptia get fleets [--tags] 
calyptia create fleet <name> [--config-file] [--tags]
```

Relate an agent to a fleet
```
calyptia update agent –fleet [name]
calyptia update agent –remove-from-fleet [name]
```

### Reviewers

- [ ] Reviewed by a team member of the @calyptia/backend team
- [ ] Reviewed by a product owner.

### Disclaimers

- If there are multiple solutions, please present each one separately.
- Save comparisons for the very end.
- Please do not create a Pull Request without creating an issue first.
- Any change needs to be discussed before proceeding.
- Failure to do so may result in the rejection of the pull request.

**Comment by pwhelan** [comment]
A check list of the current progress:

- [ ] calyptia get fleet  
- [ ] calyptia delete fleet  [--tags]
- [ ] calyptia update fleet [--config-file] [--tags]
- [ ] calyptia get fleets [--tags] 
- [ ] calyptia create fleet <name> [--config-file] [--tags]
- [ ] calyptia update agent –fleet [name]
- [ ] calyptia update agent –remove-from-fleet [name]

**Comment by pwhelan** [comment]
When listing fleets by tag it does not actually filter by them. I think this is a bug in the cloud API server.

**Comment by nicolasparada** [comment]
I'll take a look.
