### ISSUE TITLE
PreRun checks

### ISSUE THREAD

**Issue by jasmingacic** [calyptia/cli#339]
Cobra CLI has ability to run Pre and Post run operations. 
https://cobra.dev/#prerun-and-postrun-hooks

We should address those anywhere we can. 

Expanding:

There are several functionalities that are shared between CLI commands that could be wrapped into one of Cobra Command [PreRuns](https://cobra.dev/#prerun-and-postrun-hooks
) 

This isn't related to preflight checks when installing

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed. Please re-open in asana if this surfaces as a priority.
