### ISSUE TITLE
Add ownerReferences to clusterrole and clusterrolebinding

### ISSUE THREAD

**Issue by pwhelan** [calyptia/cli#347]
# New feature request

Add [ownerReferences](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta) to the clusterrole and clusterrolebinding so they are automatically garbage collected when a k8s instance is removed.

## Describe the proposal

Whenever doing cloud-e2e testing for some reason or another these two objects remain after wiping the namespace. Hopefully we could use ownerReferences is some manner, perhaps by tying it to the actual calyptia core deployment?

### Checklist for proposal reviewer

- [ ] The proposal is clear on what changes need to be made in the code base.

- [ ] The proposal is clear on the architectural changes that will be affected.

- [ ] The proposal is clear on the breaking changes and how to mitigate them.

- [ ] The proposal is clear on what the deployment/configuration strategy is.

- [ ] The proposal is clean on how testing will validate the feature implementation.

### Reviewers

- [ ] Reviewed by a team member of the @calyptia/backend team
- [ ] Reviewed by a product owner.

### Disclaimers

- If there are multiple solutions, please present each one separately.
- Save comparisons for the very end.
- Please do not create a Pull Request without creating an issue first.
- Any change needs to be discussed before proceeding.
- Failure to do so may result in the rejection of the pull request.

**Comment by nicolasparada** [comment]
Sounds great. We should add it to the helm chart too https://github.com/calyptia/charts/tree/master/charts/core

**Comment by pwhelan** [comment]
I'll do some manual tests today to see if it's actually viable.

**Comment by pwhelan** [comment]
Well... This is totally doable... but for namespaced objects only: 

https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/
> Note:
> Cross-namespace owner references are disallowed by design. Namespaced dependents can specify cluster-scoped or namespaced owners. A namespaced owner must exist in the same namespace as the dependent. If it does not, the owner reference is treated as absent, and the dependent is subject to deletion once all owners are verified absent.
> 
> Cluster-scoped dependents can only specify cluster-scoped owners. In v1.20+, if a cluster-scoped dependent specifies a namespaced kind as an owner, it is treated as having an unresolvable owner reference, and is not able to be garbage collected.
> 
> In v1.20+, if the garbage collector detects an invalid cross-namespace ownerReference, or a cluster-scoped dependent with an ownerReference referencing a namespaced kind, a warning Event with a reason of OwnerRefInvalidNamespace and an involvedObject of the invalid dependent is reported. You can check for that kind of Event by running kubectl get events -A --field-selector=reason=OwnerRefInvalidNamespace.

**Comment by jasmingacic** [comment]
An operator would be able to handle all of this. If we are to add finalizers to our objects we'd have it all.

**Comment by pwhelan** [comment]
This will be handled differently and by the operator.
