### ISSUE TITLE
Add CLI install script to core-packages.calyptia.com/install-cli.sh

### ISSUE THREAD

**Issue by jasmingacic** [calyptia/cli#350]
With availability of [install.sh](https://github.com/calyptia/cli/blob/main/install.sh) we should make the script available at  https://core-packages.calyptia.com/install-cli.sh

**Comment by patrick-stephens** [comment]
Follow https://github.com/calyptia/core-images/blob/eca842bfe0dc0ebcfebf8fbb473c5fd482278035/.github/workflows/package-build.yaml#L46

Push the actual binaries as well - let's decouple our internal git usage from a location for public consumption. It allows us to stage builds then potentially after release and also simplifies downloads of product components for testing, etc. (no private token required for access).

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed. Please re-open in asana if this surfaces as a priority.
