### ISSUE TITLE
Calyptia Install command

### ISSUE THREAD

**Issue by jasmingacic** [calyptia/cli#354]
Add a command that will:
- Run preflight checks required for Calyptia Core to run 
   - DNS
   - resolv.conf
   - Firewall 
   - systemctl or open-rc presence 
   - ...
 - install k3s cluster - This step would based on the previous check decide which flags to use to start up a k3s cluster
 - run curl checks from within the cluster
 - run nslookup check from within the cluster
 - run `calyptia create core_instance k8s | kubectl apply -f -`

Additional features:
`--force` flag to skip failed checks and provide information on what the outage is

Fixes https://github.com/calyptia/cli/issues/229

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed. Please re-open in asana if this surfaces as a priority.
