### ISSUE TITLE
Improve the command endpoint to provide the svc name

### ISSUE THREAD

**Issue by gabrielbussolo** [calyptia/cli#381]
@gabrielbussolo provide the details for getting the UUID directly with `kubectl` now but also create a CLI issue and PR to add the service name directly to `calyptia get endpoints --pipeline X` command output to simplify it.

_Originally posted by @patrick-stephens in https://github.com/calyptia/core/issues/370#issuecomment-1488342450_

**Comment by gabrielbussolo** [comment]
Today our endpoints command does not provide the service that can be used as DNS for other pipelines use as described on https://github.com/calyptia/core/issues/370#issuecomment-1490032436 
we can provide it on the endpoint command as a new column `service` or `k8s dns`.

**Comment by niedbalski** [comment]
Not on the backlog scope. Closed. Please re-open in asana if this surfaces as a priority.
