### ISSUE TITLE
Improve entire core_instance experience 

### ISSUE THREAD

**Issue by niedbalski** [calyptia/cli#60]
# Feature request

## Overall description

Improve the overall experience of booting, uninstall and switch among Calyptia core instances.

## Details

Implement a new core command. The core command will have the following sub-commands:

1. create core_instance
2. delete core_instance 
3. get core_instances

### Initial supported cloud providers are:

1. Kubernetes
2. AWS
3. GCP

### Parameter definitions:

* **Credentials** will be in the format required by the cloud provider implementation, if using k8s it will use the [kubeconfig](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) format,
if using AWS on its own [format](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html). 

* **Region** is available on cloud providers on which the calyptia-core image is available. The list of regions should be statically populated in a map[provider][]regions example [regions](https://github.com/calyptia/lts-advanced-plugin-s3-replay/blob/main/storage.go#L13).

## Sub-tasks

- AWS Support is on #106 
- GCP Support is on #107 
- Kubernetes Support is on #108

**Comment by nicolasparada** [comment]
I might have sked this, but here it comes again.
Can you install many core-daemons on the same instance?
I mean, what happens if I execute the same command many times in a row (with different aggregator name of course)?

**Comment by niedbalski** [comment]
> I might have asked this... but here it comes again.
> 
> Can you install many core-daemons on the same instance? I mean, what happens if I execute the same command many times in a row (with different aggregator name of course)? What is expected?

@nicolasparada @gabrielbussolo 

I hope this diagram simplifies a bit the workflow that we are outlining here

```mermaid
sequenceDiagram
    CLI->>+Provider: NewInstance(Cloud init params: {Project Token, Name})
    Provider->>+VM: Boot
    VM->>+Calyptia Core: StartService (calyptia-core {Env: Project Token, Env: Name})
    Calyptia Core->>+Cloud API: CreateAggregator(Params: {Project Token, Name})
    Cloud API-->>Calyptia Core: Aggregator{ID, Name, ...}
    Calyptia Core-->>+Cloud API: GetPipelines(AggregatorID)
    Calyptia Core-->>+Calyptia Core: Loop
    Provider-->>CLI: VM Started
    CLI->>+Cloud API: AggregatorByName(Name)
    Cloud API-->>CLI: Aggregator{ID, Name, ...}
    
```

**Comment by nicolasparada** [comment]
Cute, but I don't think it answers my question.

**Comment by niedbalski** [comment]
> I might have asked this... but here it comes again.
> 
> Can you install many core-daemons on the same instance? I mean, what happens if I execute the same command many times in a row (with different aggregator name of course)? What is expected?

**_1) Can you install many core-daemons on the same instance?_**

A: No each "instance" (VM/deployment) maps to a single core-daemon.

**_2) what happens if I execute the same command many times in a row (with different aggregator name of course)?_** 

A: Two "instances" (VM/deployments) will be created in the provider, 2 aggregators will be registered in the API once
the core-daemon boots up.

Does this answers your question(s)?

**Comment by nicolasparada** [comment]
Yes, thanks.

**Comment by nicolasparada** [comment]
What about something like this?

```bash
calyptia create instance gcp
calyptia create instance aws
```

`--name` is optional as the name can be autogenerated by the API.
`--env` is optional as it can use the default one.
`--creds` is optional as it searches `$HOME/.kube/config` by its own.

I guess only `--region` is gonna be required.

**Comment by nicolasparada** [comment]
Do we have a yaml recipe for a deployment and service of the core daemon?
I guess we should just follow the helm chart https://github.com/calyptia/charts/tree/master/charts/core

**Comment by nicolasparada** [comment]
Here are some examples how to connect to the k8s api from Go https://github.com/kubernetes/client-go/tree/master/examples

**Comment by niedbalski** [comment]
> What about something like this?
> 
> ```shell
> calyptia create instance gcp
> calyptia create instance aws
> ```
> 
> `--name` is optional as the name can be autogenerated by the API. `--env` is optional as it can use the default one. `--creds` is optional as it searches `$HOME/.kube/config` by its own.
> 
> I guess only `--region` is gonna be required.

@gabrielbussolo @nicolasparada 

As for parameters --creds is really up to the provider, for the AWS case it can be a local path or can be interactive
as described.

As for examples of client CLI(s) that create resources in k8s, etc. Take a look at https://github.com/up9inc/mizu/blob/2aeac6c9e6a1d3419687391c03ea968c22a2f7bc/cli/cmd/tapRunner.go#L84

**Comment by niedbalski** [comment]
====

Notes from the latest sync meeting
For the create command

**Comment by niedbalski** [comment]
I have update the lists of tasks on this task. I've removed @nicolasparada from here, as he will be switched to work on the API now. 

I am assigning the AWS tasks to myself. Leaving GCP ones to @gabrielbussolo also I've left a task for documenting the full create/update/delete for Kubernetes in cloud-docs @gabrielbussolo
