### ISSUE TITLE
Remove redundant commands

### ISSUE THREAD

**Issue by agup006** [calyptia/cli#76]
with get pipeline we can view both config and history which makes `calyptia get pipeline_config` and `calyptia get pipeline_config_history` less valuable. Can we remove these?

**Comment by nicolasparada** [comment]
They are not exactly the same, but sure we can.

**Comment by agup006** [comment]
Thanks @nicolasparada , I really like the `--only-config` option with get pipeline which I think is more than enough for most users who want to get the configuration. I'm not sure if the ID itself has value, or is usable which is why I think we should remove. If there is a scenario that perhaps I am missing though would be good to discuss

Another reason was I kept getting the following when trying to use pipeline_config by itself.

```
anugup@Anurags-MBP ~ % calyptia get pipeline_config test2           
Error: not implemented

```

**Comment by nicolasparada** [comment]
Oh, you are right. It was never implemented
https://github.com/calyptia/cli/blob/fd1d274be1109313f76be26e131f6a2242274cb7/cmd/calyptia/get_pipeline_config.go#L73-L104
The command was there cause we normally have CRUD operations on all resources, but on this one we don't have an endpoint to retrieve a single config history entry.

**Comment by nicolasparada** [comment]
@agup006 keep in mind that `calyptia get pipeline PIPELINE --include-config-history` will return the config history but only when `--output-format` is `table`.
If you want to get it in JSON, that command will not do it.

```bash
--include-config-history    Include config history in output (only available with table format)
```

In that case, the `calyptia get pipeline_config_history --pipeline PIPELINE` command was the one for it.

**Comment by agup006** [comment]
Ah I see, maybe we keep config-history and remove config then? What do you think?
